# try: 不确定是否能够正常执行的代码
# except: 异常的处理

try:
    num = int(input("请输入一个整数："))
except:
    print("请输入正确的整数！")

print("-" * 42)
